---
bootstrap_python: false
ansible_ssh_user: ubuntu
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -q ubuntu@{{ ansible_ssh_bastion_host }}"'
ansible_ssh_bastion_host: __BASTION_IP__

kubeadm_version: v1.15.0
kubernetes_version: v1.15.0
# kubernetes_api_server_address: __NLB_HOSTNAME__
# kubernetes_api_server_port: __NLB_LISTENER_PORT__

bin_dir: /usr/local/bin

cni_plugin: "calico"

kubeadm_api_server_extra_args: {}
kubeadm_controller_manager_extra_args: {}
kubeadm_scheduler_extra_args: {}
kubeadm_api_server_extra_volumes: {}
kubeadm_controller_manager_extra_volumes: {}
kubeadm_scheduler_extra_volumes: {}
kubeadm_kubelet_extra_args: {}

kubeadm_api_server_cert_extra_sans: {}

kubeadm_cluster_name: symplegma
