branches:
  only:
  - master
services:
  - docker
before_install:
  - wget https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
  - wget https://github.com/rancher/k3d/releases/download/v1.7.0/k3d-linux-amd64
  - chmod +x k3d-linux-amd64 kubectl
  - sudo mv k3d-linux-amd64 /usr/local/bin/k3d
  - sudo mv kubectl /usr/local/bin
  - k3d --version
script:
  - k3d create
  - sleep 15
  - export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
  - kubectl get node
  - kubectl apply -f flux/resources/
