dist: xenial
language: python
python:
- '3.7'
cache: pip
branches:
  only:
  - master
addons:
  ssh_known_hosts: higgs.particule.io
env:
  global:
  - BINDIR="$TRAVIS_BUILD_DIR/bin"
  - HELM_VERSION="v3.1.2"
  - KUBECTL_VERSION="v1.18.0"
  - FLUXCD_REPO="https://charts.fluxcd.io"
  - PATH="$PATH:$BINDIR"
  - KUBECONFIG="$TRAVIS_BUILD_DIR/ansible/symplegma/kubeconfig/higgs/admin.conf"
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
install:
- mkdir $BINDIR
- pip install -U ansible ansible-lint
- wget -qO- "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz" | tar xvz
  --strip-components=1 -C $BINDIR && chmod +x $BINDIR/helm && helm version --client
- helm repo add fluxcd $FLUXCD_REPO
- curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
  -o $BINDIR/kubectl && chmod +x $BINDIR/kubectl && kubectl version --client
script:
- ansible-lint ansible/common/roles/*
- ansible-playbook -b -i ansible/common/inventory/higgs/hosts ansible/common/init.yml
- ansible-playbook -b -i ansible/symplegma/inventory/higgs/hosts ansible/symplegma/symplegma-init.yml
