---
dist: xenial
language: python
python:
  - "3.7"
cache: pip

env:
  global:
    - BINDIR="$TRAVIS_BUILD_DIR/bin"
    - HELM_VERSION="v3.1.2"
    - KUBECTL_VERSION="v1.18.0"
    - FLUXCD_REPO="https://charts.fluxcd.io"
    - PATH="$PATH:$BINDIR"
    - KUBECONFIG="$TRAVIS_BUILD_DIR/ansible/symplegma/kubeconfig/higgs/admin.conf"

install:
  - mkdir $BINDIR
  - pip install -U ansible ansible-lint
  - wget -qO- "https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz" |
    tar xvz --strip-components=1 -C $BINDIR
    && chmod +x $BINDIR/helm
    && helm version --client
  - helm repo add fluxcd $FLUXCD_REPO
  - curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o $BINDIR/kubectl
    && chmod +x $BINDIR/kubectl
    && kubectl version --client

script:
  - ansible-lint ansible/common/roles/*
  - ansible-playbook -b -i common/inventory/higgs/hosts common/init.yml
  - ansible-playbook -b -i symplegma/inventory/higgs/hosts common/init.yml
