---
site_name: Symplegma
site_description: Website and documentation for symplegma project
site_author: ArchiFleKs
site_url: https://clusterfrak-dynamics.github.io/symplegma/

repo_name: clusterfrak-dynamics/symplegma
repo_url: https://github.com/clusterfrak-dynamics/symplegma

copyright: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a>

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo:
    icon: dashboard
  feature:
    tabs: true

markdown_extensions:
  - toc:
      permalink: true
  - markdown_include.include
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Overview: index.md
  - Documentation:
      - Kubernetes:
          - Kubeadm: configuration/kubeadm/kubeadm.md
      - OS:
          - Ubuntu: configuration/os/ubuntu.md
          - CoreOS: configuration/os/coreos.md
      - Networking:
          - Calico: configuration/networking/calico.md
          - HA: configuration/networking/ha.md
  - User Guides:
      - Bare-Metal: user-guides/bare-metal.md
      - AWS: user-guides/aws.md
      - OpenStack: user-guides/openstack.md
