---
- name: symplegma-os_bootstrap
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-os_bootstrap.git
  version: v1.8.0
- name: symplegma-kubernetes_hosts
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-kubernetes_hosts
  version: v1.18.0
- name: symplegma-kubeadm
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-kubeadm
  version: v1.18.0
- name: symplegma-containerd
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-containerd
  version: v1.3.3
- name: symplegma-cni
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-cni
  version: v0.8.5
- name: symplegma-calico
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-calico
  version: v3.13.2
