groups_user:
  - sudo

users:
  box:
    groups: []
    authorized_key: ""
  klefevre:
    groups:
      - sudo
      - box
    authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNBisS8Dswx8p8awTn0fkz+bAGLLl7eajy6/8nmbtRYkY/b0jajEbuEbsZl/ZVyHIsBuHQCidd64NKsi6frfL05dJbL+uLbWW6JTaZxF0YAPzWsFX5C3IssX4KS7vjC6jrokyRkEPakffRdIRvM+Tf3aY80qBOvMs8QgjLwvZYWTwFmbovsfRZfonF932qggaxjLqFVoW4XaEiilucNH3ttkejAd5xtjqyrPFOtBQITGDaF67M9Rl/12qFJR6eukplU4DgiUanXPiuKpKHc1AY6rBamg+9HHHfb4grghGuBvEjZ0I9eR5zhOnE/AB/vL4LK+ZEgaAQ1VYa7631TC87 klefevre@ocelot"
  rguichard:
    groups:
      - sudo
      - box
    authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCcS5uO7nfQZtF0kTjKzgPNFmf7iqQdKRLU0dJPSwrTlB96pl4cOkBx6FUbWJNtNhAVPKY7GaKZ630E4RQvYcVx3xD104RTyH/eXOKSOluvNuqs7jXztrKJmt9ZUW1OllIKRAhpVNGzUm1baza/I260LENhZdTmfqZT9FoqFmIyhpbnPpvQCd/a29KlNLuZHsHifL5Ognv3Z8YeKqVUKmTNJ1su7T8Qbcapz2tLS29BBQxQIiw/gtUFyTcDz0p/doem0U7KAtWl5wxJltbgr6dh5RruoWPOai6VczOPqckPdz2FgGKoIaiNgByN/J816cBvrB5g3It1CD+kEw+78qswcf2MVXT33+FLcZL0DDf0/3a9MiTdvM7Gi6TLXPE0dZs+jCsqK+bO9Dl1+TpVPg7wT5mTI/XGIoXcmlxgmURPTaXg4bfEsu4EeqSylxN8S9Dwb4h+EmGhVklH3gw0Gf77FGXbvx7ntrGRsvkNzi9S2bYU1ZGhX3eiyN5nXZWGHfjLHnY7uiLi5lTtrKAPmNcTspJ7+5NI78gESuy2Q+vrBhGwAM2IrOC7qNAea/jl8dStRif9w6DafwirM5Szd4HftmVYSNbonsfDd/sPDqJALabsR/eVpOCLsZSFQTJvOPrT1piJdJ6bRkaKXss8giJ9or1ldTWLSfBsBgPOMtDIew== rguichard@rguichard-particule"
  mhenry:
    groups:
      - box
    authorized_key: ""

vg_conf:
  seed:
    pv_list: "/dev/sda4,/dev/sdb1"
    vg_name: "seed"

lv_conf:
  seed:
    vg: "seed"
    lv: "seed"
    size: +100%FREE
    path: "/srv"
    fstype: "ext4"

